### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by chaoshengt** [johannesuhl/sequential_clustering_viz#1]
Dear @johannesuhl , thanks for sharing your code! But  there is an error 'ValueError: ndarray is not C-contiguous' when I ran the code
```python
        clust =  Birch(branching_factor=50, n_clusters=None, threshold=thresh, compute_labels=True).fit(X)
```
 how to solve it ?

**Comment by johannesuhl** [comment]
Hi @chaoshengt, thanks for using this code! I am not sure what causes this error. Could you provide information on your input array so I can reproduce the error? Also, I saw there is this numpy function: https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html --> maybe this solves the issue?

**Comment by chaoshengt** [comment]
> Hi @chaoshengt, thanks for using this code! I am not sure what causes this error. Could you provide information on your input array so I can reproduce the error? Also, I saw there is this numpy function: https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html --> maybe this solves the issue?

@johannesuhl  Yes, It works! I add the code 
```python
X = np.ascontiguousarray(X, dtype=np.float32)
```

Thank you very much!
